---
# Configuration file for pre-commit (https://pre-commit.com/)

repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: cafd5506f18eea191804850dacc0a4264772d59d # frozen: v3.0.0-alpha.4
    hooks:
      - id: prettier
        stages: [commit]
        language_version: system

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: 3f77b826548d8dc2d26675f077361c92773b50a7 # frozen: v0.9.0
    hooks:
      - id: shellcheck
        stages: [commit]
